perl-5.000b3h
http://mirrors.develooper.com/perl/really-ancient-perls/oldperl/dist/fun.tar.gz
 -> src/5.0/5.000beta/perl5.000b3h.tar.gz

diff --git a/h2xs b/h2xs
--- a/h2xs
+++ b/h2xs
@@ -1,60 +1,87 @@
-#!usr/bin/perl
+#!/usr/bin/perl
 'di ';
 'ds 00 \"';
 'ig 00 ';
 
-require 'getopts.pl';
+use Getopt::Std;
 
-$usage='h2xs [-Aachf -n name] [headerfile] [extra_libraries]
--A	Equivalent to -a -c 
--a	Omit AutoLoad facilities from .pm file.
--c	Omit the constant() function from the XS file.
--f	Force creation of the extension even if the C header does not exist.
--h	help 
--n name	Specify a name to use for the extension
-headerfile is the name of the .h file.  The full path name must be
-	used unless it is in /usr/include.
+$usage='h2xs [-Aachfm] [-n module_name] [headerfile [extra_libraries]]
+	-a	Omit AutoLoad facilities from .pm file.
+	-c	Omit the constant() function from the XS file.
+	-A	Equivalent to -a -c 
+	-f	Force creation of the extension even if the C header does not exist.
+	-m	Also create an old-style Makefile.SH
+	-h 	help
+	-n	Specify a name to use for the extension.
 extra_libraries are any libraries that might be needed for loading
-	the extension, e.g. -lm would try to link in the math library.';
+	the extension, e.g. -lm would try to link in the math library.
+';
 
-&Getopts("fhn:caA") || die "Usage: $usage\n" ;
+sub usage{ die "Usage: $usage\n" }
 
-die "Usage: $usage\n" if ( $opt_h ) ;
+getopts("fhcaAmn:") || &usage;
 
+&usage if $opt_h;
+
+if( @ARGV ){
+	$path_h = shift;
+}
+elsif( ! @ARGV && ! $opt_n ){
+	die "Must supply header file or module name\n";
+}
+
+$extralibs = "@ARGV";
 if( $opt_A ){
 	$opt_a = $opt_c = 1;
 }
+$write_makefile_sh = ($opt_m) ? 1 : 0;
 
-# Read in extra libraries.
-if ($#ARGV > 0) {   
-    $extralibs = "";
-    for (@ARGV[1..$#ARGV]) {
-	$extralibs .= "$_ ";
-    }
-    # Now make them disappear from the command line.
-    $#ARGV = 0;
+if( $path_h ){
+	$name = $path_h;
+	if( $path_h =~ s#::#/#g && $opt_n ){
+		warn "Nesting of headerfile ignored with -n\n";
+	}
+	$path_h .= ".h" unless $path_h =~ /\.h$/;
+	$path_h = "/usr/include/$path_h" unless $path_h =~ m#^[./]#;
+	die "Can't find $path_h\n" if( ! $opt_f && ! -f $path_h );
 }
 
-$name = $ARGV[0];
-$name .= ".h" unless $name =~ /\.h$/;
-$name = "/usr/include/$name" unless $name =~ m#^[./]#;
-die "Can't find $name\n" if( ! $opt_f && ! -r $name );
-$fullname = $name;
-$name =~ s#^/usr/include/##;
-$origname = $name;
-$name =~ s#^.*/##;
-$name =~ s#\.h$##;
-$module = $opt_n || "\u$name";
-chdir 'ext' if -d 'ext';
-die "Won't overwrite existing ext/$module\n" if -e "$module";
-mkdir($module, 0777) || die "Can't create ext/$module: $!\n";
-chdir($module) || die "Can't chdir ext/$module: $!\n";
-open(XS, ">$module.xs") || die "Can't create ext/$module/$module.xs: $!\n";
-open(PM, ">$module.pm") || die "Can't create ext/$module/$module.pm: $!\n";
-open(MF, ">Makefile.SH") || die "Can't create ext/$module/Makefile.SH: $!\n";
+$module = $opt_n || do {
+	$name =~ s/\.h$//;
+	if( $name !~ /::/ ){
+		$name =~ s#^.*/##;
+		$name = "\u$name";
+	}
+	$name;
+};
 
-if( -r $fullname ){
-    open(CH, "<$fullname") || die "Can't open $fullname: $!\n";
+chdir 'ext' if -d 'ext';
+
+if( $module =~ /::/ ){
+	$nested = 1;
+	@modparts = split(/::/,$module);
+	$modfname = $modparts[-1];
+	$modpname = join('/',@modparts);
+}
+else {
+	$nested = 0;
+	@modparts = ();
+	$modfname = $modpname = $module;
+}
+
+
+die "Won't overwrite existing ext/$modpname\n" if -e $modpname;
+# quick hack, should really loop over @modparts
+mkdir($modparts[0], 0777) if $nested;
+mkdir($modpname, 0777);
+chdir($modpname) || die "Can't chdir ext/$modpname: $!\n";
+
+open(XS, ">$modfname.xs") || die "Can't create ext/$modpname/$modfname.xs: $!\n";
+open(PM, ">$modfname.pm") || die "Can't create ext/$modpname/$modfname.pm: $!\n";
+
+
+if( -r $path_h ){
+    open(CH, "<$path_h") || die "Can't open $path_h: $!\n";
     while (<CH>) {
 	if (/^#[ \t]*define\s+(\w+)\b\s*[^("]/) {
 	    $_ = $1;
@@ -70,16 +97,23 @@ if( -r $fullname ){
 }
 
 $" = "\n\t";
-warn "Writing ext/$module/$module.pm\n";
+warn "Writing ext/$modpname/$modfname.pm\n";
+
 if( ! $opt_a ){
 print PM <<"END";
 package $module;
 
 require Exporter;
 require AutoLoader;
-\@ISA = (Exporter, AutoLoader, DynamicLoader);
+require DynaLoader;
+\@ISA = qw(Exporter AutoLoader DynaLoader);
+# Items to export into callers namespace by default
+# (move infrequently used names to \@EXPORT_OK below)
 \@EXPORT = qw(
 	@names
+);
+# Other items we are prepared to export if requested
+\@EXPORT_OK = qw(
 );
 
 sub AUTOLOAD {
@@ -118,10 +152,12 @@ print PM <<"END";
 package $module;
 
 require Exporter;
-\@ISA = (Exporter, DynamicLoader);
-\@EXPORT = qw(
-
-);
+require DynaLoader;
+\@ISA = qw(Exporter DynaLoader);
+# Items to export into callers namespace by default
+\@EXPORT = qw();
+# Other items we are prepared to export if requested
+\@EXPORT_OK = qw();
 
 
 bootstrap $module;
@@ -132,19 +168,22 @@ END
 
 close PM;
 
-warn "Writing ext/$module/$module.xs\n";
+warn "Writing ext/$modpname/$modfname.xs\n";
 print XS <<"END";
 #include "EXTERN.h"
 #include "perl.h"
 #include "XSUB.h"
 
 END
-if( $ARGV[0] ){
+if( $path_h ){
+	my($h) = $path_h;
+	$h =~ s#^/usr/include/##;
 print XS <<"END";
-#include <$origname>
+#include <$h>
 
 END
 }
+
 if( ! $opt_c ){
 print XS <<"END";
 static int
@@ -169,6 +208,7 @@ foreach $letter (@AZ, @az, @under) {
     last if $letter eq 'a' && !@names;
 
     print XS "    case '$letter':\n";
+    my($name);
     while (substr($names[0],0,1) eq $letter) {
 	$name = shift(@names);
 	print XS <<"END";
@@ -214,7 +254,27 @@ END
 
 close XS;
 
-warn "Writing ext/$module/Makefile.SH\n";
+{
+warn "Writing ext/$modpname/Makefile.PL\n";
+open(PL, ">Makefile.PL") || die "Can't create ext/$modpname/Makefile.PL: $!\n";
+
+# Ideally this should have a #!../.. ... miniperl etc header
+print PL <<'END';
+use ExtUtils::MakeMaker;
+# See lib/ExtUtils/MakeMaker.pm for details of how to influence
+# the contents of the Makefile being created.
+END
+print PL "&writeMakefile(\n";
+print PL "	'potential_libs' => '$extralibs',   # e.g., '-lm' \n";
+print PL "	'INC' => '',     # e.g., '-I/usr/include/other' \n";
+print PL "	'DISTNAME' => 'myname',\n";
+print PL "	'VERSION' => '0.1',\n";
+print PL ");\n";
+}
+
+if ($write_makefile_sh){
+warn "Writing ext/$modpname/Makefile.SH\n";
+open(MF, ">Makefile.SH") || die "Can't create ext/$modpname/Makefile.SH: $!\n";
 print MF <<'END';
 : This forces SH files to create target in same directory as SH file.
 : This is so that make depend always knows where to find SH derivatives.
@@ -264,6 +324,13 @@ if test -f ${ext}_BS; then
 else
 	bootdep=''
 fi
+
+case "$dlsrc" in
+dl_aix*)
+    echo "#!" > $ext.exp
+    echo "boot_$ext" >> $ext.exp
+    ;;
+esac
 
 echo "Extracting ext/$ext/Makefile (with variable substitutions)"
 : This section of the file will have variable substitutions done on it.
@@ -326,7 +393,7 @@ $spitshell >>Makefile <<'!NO!SUBS!'
 AUTO = $(TOP)/lib/auto
 INSTALLBOOT = $(AUTO)/$(EXT)/$(EXT).bs
 INSTALLDYNAMIC = $(AUTO)/$(EXT)/$(EXT).$(SO)
-INSTALLSTATIC = $(TOP)/$(EXT).a
+INSTALLSTATIC = $(EXT).a
 INSTALLPM = $(TOP)/lib/$(EXT).pm
 
 PERL = $(ABSTOP)/miniperl
@@ -364,16 +431,29 @@ $(INSTALLSTATIC):	$(EXT).o
 	$(RANLIB) $@
 	echo $(EXTRALIBS) >> $(TOP)/ext.libs
 
-$(EXT).c:	$(EXT).xs $(XSUBPP) $(TOP)/ext/typemap $(EXTTYPEMAP) $(TOP)/cflags
+$(EXT).c:	$(EXT).xs $(XSUBPP) $(TOP)/ext/typemap $(EXTTYPEMAP) $(TOP)/cflags Makefile
 	$(PERL) $(XSUBPP) $(EXT).xs >tmp
 	mv tmp $@
 
+END
+if( ! $opt_a ){
+print MF <<'END';
 $(INSTALLPM):	$(EXT).pm
+	rm -f $@
 	cp $(EXT).pm $@
 	cd $(TOP); $(PERL) autosplit $(EXT)
+END
+}
+else {
+print MF <<'END';
+$(INSTALLPM):	$(EXT).pm
+	cp $(EXT).pm $@
+END
+}
+print MF <<'END';
 
 clean:
-	rm -f *.o *.a mon.out core $(EXT).c so_locations $(BOOTSTRAP)
+	rm -f *.o *.a mon.out core $(EXT).c so_locations $(BOOTSTRAP) $(EXT).exp
 
 realclean: 	clean
 	rm -f makefile Makefile
@@ -416,10 +496,14 @@ $eunicefix Makefile
 
 END
 close MF;
+}
 
 system '/bin/ls > MANIFEST';
 
-system 'sh Makefile.SH';
+# this needs fixing
+# system '[ -f Makefile.SH ] && sh Makefile.SH';
+# system '[ -f Makefile.PL ] && perl Makefile.PL';
+
 
 ##############################################################################
 
@@ -436,16 +520,18 @@ system 'sh Makefile.SH';
 .SH NAME
 h2xs \- convert .h C header files to Perl extensions
 .SH SYNOPSIS
-.B h2xs [-f] [-A|-c|-a] [-n name] [headerfile] [extra_libraries]
+.B h2xs [-Aachfm] [-n module_name] [headerfile [extra_libraries]]
 .SH DESCRIPTION
 .I h2xs
 builds a Perl extension from any C header file.  The extension will include
 functions which can be used to retrieve the value of any #define statement
 which was in the C header.
 .PP
-The name given with -n will be used for the name of the extension.  If -n is
-not supplied then the name of the header file will be used, with the first
-character capitalized.
+The 
+.I module_name
+will be used for the name of the extension.  If module_name is not supplied
+then the name of the header file will be used, with the first character
+capitalized.
 .PP
 If the extension might need extra libraries, they should be included
 here.  The extension Makefile.SH will take care of checking whether
@@ -461,17 +547,20 @@ in the extra-libraries argument.
 Allows an extension to be created for a header even if that
 header is not found in /usr/include.
 .TP
-.B \-n name
-Specifies a name to be used for the extension.
-.TP
 .B \-a
 Omit AutoLoad(), AUTOLOAD, and autosplit from the .pm and Makefile files.
 .TP
 .B \-c
 Omit constant() from the .xs file.
 .TP
+.B \-n module_name
+Specifies a name to be used for the extension.
+.TP
 .B \-A
 Turns on both -a and -c.
+.TP
+.B \-m
+Causes an old-style Makefile.SH to be created.
 .SH EXAMPLES
 .nf
 
@@ -481,11 +570,20 @@ Turns on both -a and -c.
 	# Same, but extension is RUSERS
 	h2xs -n RUSERS rpcsvc/rusers
 
-	# Same, without AUTOLOAD, AutoLoad, autosplit
+	# Extension is rpcsvc::rusers. Still finds <rpcsvc/rusers.h>
+	h2xs rpcsvc::rusers
+
+	# Extension is ONC::RPC.  Still finds <rpcsvc/rusers.h>
+	h2xs -n ONC::RPC rpcsvc/rusers
+
+	# Without AUTOLOAD, AutoLoad, autosplit
 	h2xs -a rpcsvc/rusers
 
 	# Creates templates for an extension named RPC
-	h2xs -An RPC
+	h2xs -Afn RPC
+
+	# Extension is ONC::RPC.
+	h2xs -An ONC::RPC
 
 	# Makefile.SH will look for library -lrpc in 
 	# additional directory /opt/net/lib
